### ISSUE TITLE
App lost the ability to switch theme in tandem with OS

### ISSUE THREAD

**Issue by andrecasal** [epicweb-dev/epic-stack#163] opened 2023-06-11 18:28 UTC
Hey @kentcdodds 👋 On 07a355bd9cded21bb595678f95852bc7a2c8bc0a removed the ability for the app to adapt to OS theme changes. If the user changes the OS theme, the app doesn't adapt anymore. Was this on purpose?

**Comment by onemen** [comment] 2023-06-12 09:09
I see the same on Windows.

changing system theme only apply to the App after F5

more related issues:
- switching theme in the App does not change the value of `CH-prefers-color-scheme`, is this by design ?, I only see a change in the _session cookie.
- when user log out the App removes the _session cookie and the theme revert back to system theme from `CH-prefers-color-scheme` value.

**Comment by kentcdodds** [comment] 2023-06-12 19:22
You're right, that was a mistake. A push has been fixed.

> switching theme in the App does not change the value of `CH-prefers-color-scheme`

This is correct. That cookie value is only about what the user's prefers-color-scheme value is. That's the fallback value provided their preference is "system." Their preference is stored in the session.

> when user log out the App removes the _session cookie and the theme revert back to system theme from CH-prefers-color-scheme value.

This is a good point. We should probably have a separate cookie for the user's color scheme preference. But it's not the same as `CH-prefers-color-scheme`. The distinction is important:

1. `CH-prefers-color-scheme`: The user's system color scheme preference
2. Our new cookie (maybe simply `theme`?): The user's preference for our app. When "system", we reference the `CH-prefers-color-scheme` value.

This So yes, this is a bug and should be fixed by adding a separate cookie for managing the theme. No need to sign it either. It can be a raw value.

**Closed** 2023-06-13 16:29 UTC
Labels: bug
