### ISSUE TITLE
Improve lighthouse score

### ISSUE THREAD

**Issue by kasperpeulen** [epicweb-dev/epic-stack#473] opened 2023-10-05 09:04 UTC
Most other pages than the landing page have a 100 score, but it would be nice if the landing page would also be EPIC 😄 :
<img width="899" alt="image" src="https://github.com/epicweb-dev/epic-stack/assets/1035299/dae5e4ed-5130-4b36-a373-9d3418885d88">

Besides that, it would be really cool if the epic stack would have performance regression tests, so that the lighthouse score stays great over time!

**Comment by calciferlo** [comment] 2023-10-09 19:12
Hi. I change png/jpg images to webp and resize this stars image to be the same height-width as container and I have this score on production build.
![CleanShot 2023-10-09 at 21 10 22@2x](https://github.com/epicweb-dev/epic-stack/assets/8167068/852a03ce-005c-4505-80bd-302a0b20667a)

**Comment by kiliman** [comment] 2023-10-09 20:06
Unless your app is going to have the big banner image and vendor logos, I wouldn't worry about it. Check the Lighthouse score against your *own* content.

If the score is low even without images, then that would be something that should be investigated.

**Comment by calciferlo** [comment] 2023-10-10 09:25
I think this is not the case, I love Remix... but I recreate the same html with styles and logos in latest version of Next.js and results is awesome.
![CleanShot 2023-10-10 at 11 22 57@2x](https://github.com/epicweb-dev/epic-stack/assets/8167068/320dc76b-5f69-4b89-8dc0-ccb133c9f479)

**Comment by calciferlo** [comment] 2023-10-12 08:26
Yes localhost. Maybe it's not reliable as much but we have significant different in score. But for better use case, we need to provide score vs score after deploy example on Vercel, fly, etc.

**Comment by kentcdodds** [comment] 2023-10-12 12:39
The very best way to get these scores is via https://www.webpagetest.org/ (you can run a full lighthouse test on there).

Don't get me wrong, I definitely want to look at improving this. I just want to make sure we know what we're improving.

**Comment by kasperpeulen** [comment] 2023-10-18 19:04
I tried it now with https://web.dev/measure:

https://pagespeed.web.dev/analysis/https-kasperpeulen-com/fr08icnb8h?form_factor=mobile

<img width="1042" alt="image" src="https://github.com/epicweb-dev/epic-stack/assets/1035299/5e3f8377-6fe5-4112-95f9-61b6bbb5fb6c">

@calciferlo Could you deploy your next.js remake somewhere?

**Comment by sergiodxa** [comment] 2023-10-18 19:11
Also don't just replicate the HTML, replicate everything that may be happening server-side in loaders, or client-side, e.g. the Client Hints that does a reload

**Comment by kentcdodds** [comment] 2023-10-31 11:23
I got a lighthouse score of 97 on the user profile page: https://pagespeed.web.dev/analysis/https-www-epicstack-dev-users-kentcdodds/j1abp4iunu?form_factor=mobile

So I'm pretty sure the issue is related to the images hosted by GitHub on the home page. Because this is something people will remove, I'm not concerned. But I'm sure there are areas of improvement we could make. However, I'd prefer specific issues be filed so I'm going to close this one. Feel free to open issues and pull requests for specific things.

Cheers!

**Closed by kentcdodds** 2023-10-31 11:23 UTC
