### ISSUE TITLE
dev command only starts server, not spinning up the ui

### ISSUE THREAD

**Issue by swalker326** [epicweb-dev/epic-stack#12] opened 2023-05-11 15:40 UTC
Running `npm run dev` only starts the server. 

<img width="523" alt="Screenshot 2023-05-11 at 9 39 30 AM" src="https://github.com/epicweb-dev/epic-stack/assets/8460808/71a39cc0-5845-4859-a937-80cbfd205b01">

**Comment by kentcdodds** [comment] 2023-05-11 15:43
Thanks for looking into the stack @swalker326! I'm afraid I can't reproduce this issue.

<img width="932" alt="image" src="https://github.com/epicweb-dev/epic-stack/assets/1500684/513e6d2e-1986-49d6-8be8-295674323508">

Could you dig a little more?

**Comment by kentcdodds** [comment] 2023-05-11 16:52
Ah, yeah, this project uses `npm` so I'll close this out. Happy to accept a PR to make `pnpm` work if it doesn't negatively impact the experience of anything else. Thanks!

**Closed by kentcdodds** 2023-05-11 16:52 UTC
Labels: help wanted, can't reproduce
