### ISSUE TITLE
Fix flaky tests

### ISSUE THREAD

**Issue by andrecasal** [epicweb-dev/epic-stack#186] opened 2023-06-15 10:29 UTC
After [fixing the flaky logout](https://github.com/epicweb-dev/epic-stack/pull/185), the logout POST request is not canceled in the browser anymore, but it's still aborted on Playwright tests. This causes the test to be flaky.

```ts
//...
await page.getByRole('link', { name: user.name ?? user.username }).click()
await page.getByRole('menuitem', { name: /logout/i }).click()
await expect(page).toHaveURL(`/`) // 👈 This doesn't help

await page.goto('/login')
await expect(page).toHaveURL(`/login`)
//...
```

![Screenshot 2023-06-15 at 11 02 35](https://github.com/epicweb-dev/epic-stack/assets/22457463/9d1633fe-e7a6-4419-b67a-efb6734bad1a)

**Comment by andrecasal** [comment] 2023-06-15 10:31
Running `npx playwright test` passes most of the time, but sometimes fails:
![Screenshot 2023-06-15 at 11 30 38](https://github.com/epicweb-dev/epic-stack/assets/22457463/acffde1e-ecb0-4d3a-add8-795b28ce5e0e)

**Comment by andrecasal** [comment] 2023-06-15 21:29
No, they are different tests. Yeah, I'm not sure either 🤔 I'll update the issue if this keeps bugging and possibly a solution.

**Comment by andrecasal** [comment] 2023-06-27 15:19
ba56bf27a475eba34a20b990e6f3c41c9e9df4af still didn't fix it 🙂

**Comment by kentcdodds** [comment] 2023-06-27 18:16
Bummer. I've not personally experienced any flakiness with the tests, so I'm afraid I don't know how to help with this :(

**Comment by andrecasal** [comment] 2023-06-29 10:54
Yeah, they fail to load routes sometimes, no idea why...

Two tests, one minute apart:
<img width="1920" alt="Screenshot 2023-06-29 at 11 52 30" src="https://github.com/epicweb-dev/epic-stack/assets/22457463/32fd9c32-218e-4d48-b92c-e66b70846bdf">
<img width="1920" alt="Screenshot 2023-06-29 at 11 53 40" src="https://github.com/epicweb-dev/epic-stack/assets/22457463/6ecd8ba7-4ec3-487a-b428-77c3c1d45701">

**Comment by kentcdodds** [comment] 2023-06-29 14:11
Sadly because I'm unable to reproduce I can't work on this myself

**Comment by kentcdodds** [comment] 2023-07-07 06:29
As I cannot reproduce, I am going to close this issue.

**Closed by kentcdodds** 2023-07-07 06:29 UTC
