### ISSUE TITLE
Hydration error when rendering input fields

### ISSUE THREAD

**Issue by rajeshg** [epicweb-dev/epic-stack#98] opened 2023-05-25 15:32 UTC
It seems that there is a hydration or value mismatch on input fields rendered. 2 places that I have noticed is on the **login** page and **/users/kody/notes/new** page

Here is the warning that I see on the browser console:
>
`
react-dom.development.js:86 Warning: Prop `required` did not match. Server: "null" Client: "true"
    at input
    at div
    at Field (http://localhost:3000/build/_shared/chunk-BSZPZSYR.js:962:3)
    at form
    at http://localhost:3000/build/_shared/chunk-BCML5FIO.js:4972:9
    at fetcher.Form
    at NoteEditor (http://localhost:3000/build/_shared/chunk-PDY3WINQ.js:73:3)
    at NewNoteRoute
    at RemixRoute (http://localhost:3000/build/_shared/chunk-BCML5FIO.js:5795:3)
    at RenderedRoute (http://localhost:3000/build/_shared/chunk-BCML5FIO.js:3482:5)
    at Outlet (http://localhost:3000/build/_shared/chunk-BCML5FIO.js:3810:26)
    at main
    at div
    at div
    at NotesRoute (http://localhost:3000/build/routes/users+/$username_+/notes-JGNJTVY3.js:61:16)
    at RemixRoute (http://localhost:3000/build/_shared/chunk-BCML5FIO.js:5795:3)
    at RenderedRoute (http://localhost:3000/build/_shared/chunk-BCML5FIO.js:3482:5)
    at RenderErrorBoundary (http://localhost:3000/build/_shared/chunk-BCML5FIO.js:4029:9)
    at Outlet (http://localhost:3000/build/_shared/chunk-BCML5FIO.js:3810:26)
    at div
    at body
    at html
    at App (http://localhost:3000/build/root-3JJ2C4UT.js:3216:16)
    at RemixRoute (http://localhost:3000/build/_shared/chunk-BCML5FIO.js:5795:3)
    at RenderedRoute (http://localhost:3000/build/_shared/chunk-BCML5FIO.js:3482:5)
    at RenderErrorBoundary (http://localhost:3000/build/_shared/chunk-BCML5FIO.js:4029:9)
    at DataRoutes (http://localhost:3000/build/_shared/chunk-BCML5FIO.js:3745:5)
    at Router (http://localhost:3000/build/_shared/chunk-BCML5FIO.js:3817:15)
    at RouterProvider (http://localhost:3000/build/_shared/chunk-BCML5FIO.js:3701:5)
    at RemixErrorBoundary (http://localhost:3000/build/_shared/chunk-BCML5FIO.js:5357:5)
    at RemixBrowser (http://localhost:3000/build/_shared/chunk-BCML5FIO.js:7307:40)
`

Adding a console.log statement on the note-editor, I see the following:
Server-side
>
`
conform input {
  id: 'note-editor-title',
  name: 'title',
  form: 'note-editor',
  required: undefined,
  type: undefined,
  minLength: undefined,
  maxLength: undefined,
  min: undefined,
  max: undefined,
  step: undefined,
  pattern: undefined,
  multiple: undefined,
  defaultValue: undefined
}
`

On the client:
>
`
conform input {
  defaultValue: undefined,
  form: "note-editor",
  id: "note-editor-title",
  max: undefined,
  maxLength: undefined,
  min: undefined,
  minLength: 1,
  multiple: undefined,
  name: "title",
  pattern: undefined,
  required: true,
  step: undefined,
  type: undefined,
}
`

@edmundhung could this be a conform thing or something else from how react components are rendered?

**Comment by edmundhung** [comment] 2023-05-25 20:03
I can reproduce the problem locally with the latest version of epic stack. But the server gives a slightly different answer when I log the result from `getFieldsetConstraint(NoteEditorSchema)`: On the server, it always returns an empty object. This kind of explain why it sees a different value between server and client and print the warning.

After some extra inpsection, it looks like the server is running two copy of `zod` (1 esm and 1 cjs) and so `getFieldsetConstraint()` fails to recognize the zod schema class. I am not sure why this happens though. 😅

**Comment by kentcdodds** [comment] 2023-05-26 06:03
That is very strange! I wonder if it has to do with the weird stuff we're doing for Hot Data Revalidation 🤔 https://github.com/epicweb-dev/epic-stack/blob/ea4ff766b8ffd3efd3b229c8166c9f4e281263ec/server/index.ts#L112

Really doesn't seem like that should happen, but maybe?

**Comment by kentcdodds** [comment] 2023-05-26 06:07
I've confirmed that we are indeed loading both the cjs and esm on the server, even before doing HDR. I'm still determining where those imports are coming from.

**Comment by kentcdodds** [comment] 2023-05-26 06:11
Ah, I found it. It's coming from `@conform-to/zod` which runs `require('zod')` which will naturally resolve to the cjs version of zod due to zod's exports config in its package.json:

```json
  "exports": {
    ".": {
      "require": "./lib/index.js",
      "import": "./lib/index.mjs",
      "types": "./index.d.ts"
    },
    "./package.json": "./package.json",
    "./locales/*": "./lib/locales/*"
  },
```

I'm not sure how to fix this issue. But it stems from the fact we're using native ESM in the epic stack. Of course that's the problem 🤦‍♂️

**Comment by edmundhung** [comment] 2023-05-26 06:19
Thanks for looking into it Kent! I am not familiar with the ESM setup but am I correct to say this can be resolved if Conform has ESM supported? I can look into it today (probably copying some build config elsewhere 😅 )

**Comment by kentcdodds** [comment] 2023-05-26 06:55
I think if conform added support for ESM that would resolve this, yes.

**Comment by edmundhung** [comment] 2023-05-29 07:44
This is fixed on `v0.7.0-pre.0`, which has no other changes except the esm setup after v0.6.3. Feel free to pin to this version if needed.

**Comment by rajeshg** [comment] 2023-05-30 16:11
I can confirm that `v0.7.0-pre.1` fixes this. @edmundhung Thanks for adding the ESM support to conform

**Comment by kentcdodds** [comment] 2023-06-01 17:28
Great! Let me know when this gets an official release and we'll upgrade the stack :)

**Comment by kentcdodds** [comment] 2023-06-07 15:30
I upgraded to the pre release because this was annoying me.

**Closed by kentcdodds** 2023-06-07 15:30 UTC
