### ISSUE TITLE
2FA not working with Google Authenticator?

### ISSUE THREAD

**Issue by Mat-moran** [epicweb-dev/epic-stack#257] opened 2023-07-03 13:52 UTC
Hi,

I was testing the 2FA authentication flow when I realised that is not working with Google Authenticator App. With other providers works well.

## Steps to reproduce
- Create a brand new epic stack app
- Start the development server
- Create an account
- Try to enable 2FA reading the QR code with google Authenticator app (I am using version 4.0.1 of this app in IOS 16.5.1)
- You should get an error saying that the code is not valid.

I have tried in IOS and in Android without success.

**Comment by amir-ziaei** [comment] 2023-07-03 15:52
Just tried it out on my end and it seems like the issue is within the QR code. Because it works when I enter the `secret` manually into Google Authenticator.

More, I also tried the manual flow with 1Password and everything seemed fine. Except, 1Password doesn't seem to be able to recognize there is a QR Code on the page to offer its auto-scanning feature. Maybe it needs some hints? Further investigation might be nice.

**Comment by mediabakery** [comment] 2023-07-05 08:46
I found the issue. Contrary to what the documentation suggests, google authenticator evaluates the algorithm field and only accepts uppercase.

**Comment by kentcdodds** [comment] 2023-07-05 16:24
Merged. Thank you very much!

**Closed by kentcdodds** 2023-07-05 16:24 UTC
Labels: bug
